<?php

    namespace app\components;

    use yii\widgets\ActiveField;
    use yii\helpers\Html;


    class SwitcherWidget extends  ActiveField
    {


        /**
        @inheritDoc
         */
        public function init()
        {
            parent::init(); // TODO: Change the autogenerated stub
        }
        /**
        @inheritDoc
         */
        public function run()
        {
            parent::run(); // TODO: Change the autogenerated stub
        }
    }